import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<main className="bg-[radial-gradient(115.63%_58.45%_at_102.06%_72.19%,_#83a4c8_0%,_#5f81a7_29.42%,_#304965_56.5%,_#2b3e54_65.62%,_#212834_90.74%,_#202327_100%)]">
					{children}
				</main>
			</body>
		</html>
	);
}
